spring:
  application:
    name: RestSpring
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/RestSpring?useTimezone=true&serverTimezone=UTC
    username: root
    password: M@109G6Gustav
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    root: WARN
    br.dev.md: DEBUG